image: node:latest

services:
  - mongo:latest

stages:
  - setup
  - test
  - deploy

cache:
  paths:
    - ./app/server/node_modules/

install_dependencies:
  stage: setup
  script:
    - echo "Installing Node.js dependencies..."
    - cd ./app/server
    - npm install
  artifacts:
    paths:
      - ./app/server/node_modules/

run_tests:
  stage: test
  script:
    - echo "Running tests..."
    - cd ./app/server
    - npm test
  only:
    - testing 

deploy:
  stage: deploy
  script:
    - echo "Hello World"
  only:
    - main 